from python:3.13.3-alpine

WORKDIR /app

COPY main.py .
COPY pyproject.toml .
COPY settings.toml .
COPY ./app ./app
RUN pip install uv
RUN uv pip install -r pyproject.toml --system

ENV ENV_FOR_DYNACONF=production

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]